### ISSUE TITLE
loop connection problem http://192.168.0.113:8000/Win11_EnglishInternational_x64v1.iso

### ISSUE THREAD

**Issue by bugbounted** [Filadeus/windows11-in-docker#4]
Hi [Filadeus](https://github.com/Filadeus),
I'm giving error below & can't be solve by container :
`[0m[91m--2022-06-08 18:55:02-- (try: 4) http://192.168.0.113:8000/Win11_EnglishInternational_x64v1.iso
1202 | [0m[91mConnecting to 192.168.0.113:8000... [0m[91mfailed: Connection timed out.
1203 | [0m[91mRetrying.`
see full image build log here :
https://gist.github.com/elmirarokni/d69a44d422fdc1c0c1f3fd291a91ca0b

**Comment by Filadeus** [comment]
Hi! Thanks for the interest in my project! I'm sorry but I haven't touched it in some time. I do remember making changes to Dockerfile in beta branch to download Windows ISO faster from my local NAS. But I don't remember merging changes from beta to main branch. Anyway since someone got interested, I will try make some useful changes to Dockerfile in the next few hours.
